language: java

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov
  
after_success:
  - codecov
  
notifications:
  email:
    recipients:
      - builds@starchartlabs.org
    on_success: change
    on_failure: always
